

export const QUERY_KEY = {
    USERS: 'USERS',
    DEPARTMENTS: 'DEPARTMENTS',
    ACADEMIC_BATCH: 'ACADEMIC_BATCH',
    SEMESTERS: 'SEMESTERS',
    SUBJECTS: 'SUBJECTS',
    STUDENTS: 'STUDENTS',
    CURRICULAM: 'CURRICULAM',
    FACULTIES:'FACULTIES',

    ALL_DEPARTMENTS: 'ALL_DEPARTMENTS',
    ALL_SUBJECTS: 'ALL_SUBJECTS',
    ALL_SEMESTERS: 'ALL_SEMESTERS',
    ALL_ACADEMIC_BATCHES: 'ALL_ACADEMIC_BATCHES',
}
