

export const DB_NAME = {
  BED: 'bed',
  ROOMS: 'rooms',
  RESIDENT: "resident",
  COMPANY: "company",
  LOCAL_AUTHORITY: 'localAuthority',
  ICB: 'icb',
  FNM: 'fnc',
  INVOICE: 'invoice',
  USER: 'user',
  BANK_DETAILS: 'bankDetails',
  CREDIT_WALLET: 'creditWallet',
  VAT_MASTER: 'vatMaster ',
  MISCELLANEOUS_MASTER: 'miscellaneousMaster ',
  DUE_DATE_MASTER: 'dueDateMaster',
  BILLING_PATTERN_MASTER: 'billingPatternMaster',
  RESIDENT_DOCUMENT: 'residentDocument',
  ROOM_REPORT: 'roomReport',
  RELATIONSHIP_MASTER: 'relationshipMaster',
  OPENING_BALANCE: 'openingBalance',
  CHART_OF_ACCOUNT: 'chartOfAccounts',
  FOLLOW_UP: "followUps",
  VENDOR: "vendor",
  PRODUCT_CATEGORY: "productCategory",
  PRODUCT: "product",
  PURCHASE_ORDER: "purchaseOrder",
  NOTIFICATION: 'notification',
  UNIT_OF_MEASUREMENT: 'unitOfMeasurement',
  BLOCK_BED_REPORT: "blockBedReport",
  HEAD_OFFICE_ADDRESS: 'headOfficeAddress',
  DISCOUNT: 'discount',
  DEBIT_NOTE: 'debitNote',
  PURCHASE_BILL: 'purchaseBill',
}
